/**
 * openapi server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QVariantMap>
#include <QDebug>

#include "OAIHelpers.h"
#include "OAIOkaserverApiRequest.h"

namespace OpenAPI {

OAIOkaserverApiRequest::OAIOkaserverApiRequest(QHttpEngine::Socket *s, QSharedPointer<OAIOkaserverApiHandler> hdl) : QObject(s), socket(s), handler(hdl) {
    auto headers = s->headers();
    for(auto itr = headers.begin(); itr != headers.end(); itr++) {
        requestHeaders.insert(QString(itr.key()), QString(itr.value()));
    }
}

OAIOkaserverApiRequest::~OAIOkaserverApiRequest(){
    disconnect(this, nullptr, nullptr, nullptr);
    qDebug() << "OAIOkaserverApiRequest::~OAIOkaserverApiRequest()";
}

QMap<QString, QString>
OAIOkaserverApiRequest::getRequestHeaders() const {
    return requestHeaders;
}

void OAIOkaserverApiRequest::setResponseHeaders(const QMultiMap<QString, QString>& headers){
    for(auto itr = headers.begin(); itr != headers.end(); ++itr) {
        responseHeaders.insert(itr.key(), itr.value());
    }
}


QHttpEngine::Socket* OAIOkaserverApiRequest::getRawSocket(){
    return socket;
}


void OAIOkaserverApiRequest::getokainfoRequest(){
    qDebug() << "/okaserver";
    connect(this, &OAIOkaserverApiRequest::getokainfo, handler.data(), &OAIOkaserverApiHandler::getokainfo);

    


    emit getokainfo();
}



void OAIOkaserverApiRequest::getokainfoResponse(const OAIOkaserver& res){
    setSocketResponseHeaders();
    QJsonDocument resDoc(::OpenAPI::toJsonValue(res).toObject());
    socket->writeJson(resDoc);
    if(socket->isOpen()){
        socket->close();
    }
}


void OAIOkaserverApiRequest::getokainfoError(const OAIOkaserver& res, QNetworkReply::NetworkError error_type, QString& error_str){
    Q_UNUSED(error_type); // TODO: Remap error_type to QHttpEngine::Socket errors
    setSocketResponseHeaders();
    Q_UNUSED(error_str);  // response will be used instead of error string
    QJsonDocument resDoc(::OpenAPI::toJsonValue(res).toObject());
    socket->writeJson(resDoc);
    if(socket->isOpen()){
        socket->close();
    }
}


void OAIOkaserverApiRequest::sendCustomResponse(QByteArray & res, QNetworkReply::NetworkError error_type){
    Q_UNUSED(error_type); // TODO
    socket->write(res);
    if(socket->isOpen()){
        socket->close();
    }
}

void OAIOkaserverApiRequest::sendCustomResponse(QIODevice *res, QNetworkReply::NetworkError error_type){
    Q_UNUSED(error_type);  // TODO
    socket->write(res->readAll());
    if(socket->isOpen()){
        socket->close();
    }
}

}
