/**
 * openapi server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIOkaserver.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIOkaserver::OAIOkaserver(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIOkaserver::OAIOkaserver() {
    this->initializeModel();
}

OAIOkaserver::~OAIOkaserver() {}

void OAIOkaserver::initializeModel() {

    m_id_isSet = false;
    m_id_isValid = false;
}

void OAIOkaserver::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIOkaserver::fromJsonObject(QJsonObject json) {

    m_id_isValid = ::OpenAPI::fromJsonValue(id, json[QString("id")]);
    m_id_isSet = !json[QString("id")].isNull() && m_id_isValid;
}

QString OAIOkaserver::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIOkaserver::asJsonObject() const {
    QJsonObject obj;
    if (m_id_isSet) {
        obj.insert(QString("id"), ::OpenAPI::toJsonValue(id));
    }
    return obj;
}

QString OAIOkaserver::getId() const {
    return id;
}
void OAIOkaserver::setId(const QString &id) {
    this->id = id;
    this->m_id_isSet = true;
}

bool OAIOkaserver::is_id_Set() const{
    return m_id_isSet;
}

bool OAIOkaserver::is_id_Valid() const{
    return m_id_isValid;
}

bool OAIOkaserver::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_id_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIOkaserver::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_id_isValid && true;
}

} // namespace OpenAPI
